### ISSUE TITLE
Unable to build on Gentoo 4.17.10 kernel

### ISSUE THREAD

**Issue by promi** [ulli-kroll/mt7610u#79]
I tried building the driver with Gentoo running a 4.17.10 kernel.

It fails with this compiler error:

```
l@gentoo-flausch ~/mt7610u $ LANG=C make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.17.10-gentoo/build M=/home/l/mt7610u modules
make[1]: Entering directory '/usr/src/linux-4.17.10-gentoo'
  CC [M]  /home/l/mt7610u/os/linux/rt_linux.o
/home/l/mt7610u/os/linux/rt_linux.c: In function 'RtmpOSNetDevAttach':
/home/l/mt7610u/os/linux/rt_linux.c:1144:13: error: 'struct net_device' has no member named 'wireless_handlers'; did you mean 'rx_handler'?
    pNetDev->wireless_handlers = &rt28xx_iw_handler_def;
             ^~~~~~~~~~~~~~~~~
             rx_handler
make[2]: *** [scripts/Makefile.build:313: /home/l/mt7610u/os/linux/rt_linux.o] Error 1
make[1]: *** [Makefile:1571: _module_/home/l/mt7610u] Error 2
make[1]: Leaving directory '/usr/src/linux-4.17.10-gentoo'
make: *** [Makefile:370: modules] Error 2

```

I also tries Linux 4.14.52 with the same error message.

Is there something in the Makefile that I have to set?

**Comment by promi** [comment]
I asked for assistance on the Gentoo Forums:

https://forums.gentoo.org/viewtopic-t-1087264-start-0-postdays-0-postorder-asc-highlight-.html

The error goes away when I include another WIFI driver in the .config file that uses the WIRELESS_EXT feature.

For example I enabled CONFIG_IPW2200 (Intel PRO/Wireless 2200BG and 2915ABG Network Connection) which turns on WIRELESS_EXT. After rebuilding the kernel the mt7610u driver built successfully.
