### ISSUE TITLE
Doesn't build on Linux 4.15

### ISSUE THREAD

**Issue by unixfox** [ulli-kroll/mt7610u#61]
I can't build the mt7610u module on Linux kernel 4.15.2.
Here are the logs:
```
<command-line>:0:0: note: this is the location of the previous definition
/var/lib/dkms/mt7610u_sta/1.0/build/os/linux/../../os/linux/rt_linux.c: In function '__RTMP_OS_Init_Timer':
/var/lib/dkms/mt7610u_sta/1.0/build/os/linux/../../os/linux/rt_linux.c:117:3: error: implicit declaration of function 'init_timer'; did you mean 'init_timers'? [-Werror=implicit-function-declaration]
   init_timer(pTimer);
   ^~~~~~~~~~
   init_timers
/var/lib/dkms/mt7610u_sta/1.0/build/os/linux/../../os/linux/rt_linux.c:118:9: error: 'OS_NDIS_MINIPORT_TIMER {aka struct timer_list}' has no member named 'data'
   pTimer->data = (unsigned long)data;
         ^~
/var/lib/dkms/mt7610u_sta/1.0/build/os/linux/../../os/linux/rt_linux.c:119:20: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
   pTimer->function = function;
                    ^
```

It's because with the Linux version 4.15-rc1, the old interface init_timer() is no longer available:
>With version 4.15-rc1, conversion to new timer interface is finished and
old interface using init_timer() is no longer available. Convert both users
to new one.

-[mkubecek](https://github.com/mkubecek/vmware-host-modules/commit/562121d7bc06)

**Comment by ulli-kroll** [comment]
Thanks for the link.
This is a really simple solution for this, I will use this as some temple.

**Comment by rallep71** [comment]
/home/ralf/TP/mt7610u/os/linux/rt_linux.c: In Funktion »RTMP_OS_Init_Timer«:
/home/ralf/TP/mt7610u/os/linux/rt_linux.c:2615:3: Fehler: Implizite Deklaration der Funktion »init_timer«; meinten Sie »init_timers«? [-Werror=implicit-function-declaration]
   init_timer(pTimer);
   ^~~~~~~~~~
   init_timers
/home/ralf/TP/mt7610u/os/linux/rt_linux.c:2616:9: Fehler: »struct timer_list« hat kein Element namens »data«
   pTimer->data = (unsigned long)data;
         ^~
/home/ralf/TP/mt7610u/os/linux/rt_linux.c:2617:20: Fehler: Zuweisung von inkompatiblem Zeigertyp [-Werror=incompatible-pointer-types]
   pTimer->function = function;
                    ^
cc1: Einige Warnungen werden als Fehler behandelt
make[2]: *** [scripts/Makefile.build:317: /home/ralf/TP/mt7610u/os/linux/rt_linux.o] Fehler 1
make[1]: *** [Makefile:1510: _module_/home/ralf/TP/mt7610u] Fehler 2
make[1]: Verzeichnis „/usr/lib/modules/4.15.5-1-ARCH/build“ wird verlassen
make: *** [Makefile:370: modules] Fehler 2

**Comment by unixfox** [comment]
@ulli-kroll any updates on the patch?

**Comment by ulli-kroll** [comment]
Hi, please test current master
tested with v4.15.6

**Comment by JMSarDev** [comment]
It compiles and works fine on 4.15 (Manjaro KDE), however the drivers it's not working with my TP-LINK T2UH.

Basically the moment I do the "sudo insmod mt7610u.ko", all the network related settings, CLI tools stop working.

**Comment by unixfox** [comment]
@JMSarDev it's a known issue related to NetworkManager: #60 #52 #21
