### ISSUE TITLE
Doesn't build on RPI3 Raspbian 4.9.59-v7+

### ISSUE THREAD

**Issue by DJDan** [ulli-kroll/mt7610u#62]
I am trying to get this to work with my "TP-Link Archer T2UH" on Raspberry Pi 3 but keep getting build errors.

uname -a
Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

Firstly it complains that there is no /lib/modules/4.9.59-v7+/build directory.
When I 'mkdir' and create the empty build dir it then does the following error.

pi@raspberrypi:~/Downloads/mt7610u $ make
make ARCH=armv7l CROSS_COMPILE= -C /lib/modules/4.9.59-v7+/build M=/home/pi/Downloads/mt7610u modules
make[1]: Entering directory '/lib/modules/4.9.59-v7+/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/lib/modules/4.9.59-v7+/build'
Makefile:371: recipe for target 'modules' failed
make: *** [modules] Error 2

How do I actually get this to compile?

====

I manually changed ARCH to "arm" rather then "armv7l" and get a little closer.
But why does it still error?

====

make ARCH=arm CROSS_COMPILE= -C /lib/modules/4.9.59-v7+/build M=/home/pi/Downloads/mt7610u modules
make: Entering directory '/usr/src/linux-headers-4.9.59-v7+'
  CC [M]  /home/pi/Downloads/mt7610u/os/linux/rt_profile.o
/home/pi/Downloads/mt7610u/os/linux/rt_profile.c:28:23: fatal error: rt_config.h: No such file or directory
 #include "rt_config.h"
                       ^
compilation terminated.
scripts/Makefile.build:293: recipe for target '/home/pi/Downloads/mt7610u/os/linux/rt_profile.o' failed
make[1]: *** [/home/pi/Downloads/mt7610u/os/linux/rt_profile.o] Error 1
Makefile:1493: recipe for target '_module_/home/pi/Downloads/mt7610u' failed
make: *** [_module_/home/pi/Downloads/mt7610u] Error 2
make: Leaving directory '/usr/src/linux-headers-4.9.59-v7+'

**Comment by DJDan** [comment]
NOTE: The default make script was building it wrongly and trying to cross compile and putting wrong parameters for some reason.
I manually typed in the following command and it seems to compile.
make ARCH=arm

**Comment by ulli-kroll** [comment]
Normally I don't do this ...
I have to quote my Readme.md
> If the driver fails building consult your distro how to
> install the kernel sources and build an external module.
> 
> Questions about this will silently ignored !
> They are plenty information around the web.

So

> Firstly it complains that there is no /lib/modules/4.9.59-v7+/build directory.
> When I 'mkdir' and create the empty build dir it then does the following error.

/lib/modules/$(uname -r)/build 
is not found, because you have **no** kernel sources installed.
This symlink (if set from kernel source install) points to the **right** directory 
You need a valid .config from your running kernel.
`/proc/config.gz`
should help here.
Also the kernel sources must be prepared to build an external module.
The easiest way is to run
`make`
or
`make modules_prepare`
in your kernel directory

If the mt7610u  module build complains about missing compiler, mostly on arm you can use
`CROSS_COMPILER=`
to override this.

Pro tip
If you build the kernel as user root, you are doing something wrong
